allowBuilds:
  '@fission-ai/openspec': true
  '@netlify/content-engine': true
  '@parcel/watcher': true
  better-sqlite3: true
  core-js: true
  es5-ext: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
