import assert from 'node:assert/strict';
import fs from 'node:fs';

const workflow = fs.readFileSync('.github/workflows/editorial-publication.yml', 'utf8');
const publicationScript = fs.readFileSync('scripts/editorial-publication.ts', 'utf8');
const qualityWorkflow = fs.readFileSync('.github/workflows/quality-gates.yml', 'utf8');
const dashboard = fs.readFileSync('tina/dashboard/EditorialDashboard.tsx', 'utf8');
const netlifyConfig = fs.readFileSync('netlify.toml', 'utf8');
const packageJson = fs.readFileSync('package.json', 'utf8');

assert.match(workflow, /branches:\s*\n\s*- editorial\/tina/);
assert.match(workflow, /paths:\s*\n\s*- src\/data\/editorial\/publication-request\.json/);
assert.match(workflow, /cancel-in-progress: false/);
assert.match(workflow, /actions: write/);
assert.match(workflow, /editorial-publication\.ts preflight/);
assert.match(workflow, /gh workflow run quality-gates\.yml --ref editorial\/tina/);
assert.match(workflow, /commits\/\$\{GITHUB_SHA\}\/check-runs/);
assert.match(workflow, /quality_status/);
assert.match(workflow, /quality_conclusion/);
assert.match(workflow, /gh pr merge/);
assert.match(workflow, /--title "Publicación editorial/);
assert.doesNotMatch(workflow, /--title "\[skip netlify\]/);
assert.match(workflow, /wait-for-production-marker\.mjs/);
assert.match(workflow, /mark-progress \\\r?\n\s*deploying/);
assert.match(workflow, /waiting_index/);
assert.match(workflow, /deploy_not_confirmed/);
assert.match(workflow, /Confirm production serves the integrated commit[\s\S]*Record confirmed publication[\s\S]*mark-published/);
assert.match(publicationScript, /function writePublishedResult[\s\S]*buildEditorialProductionIndex/);
assert.match(publicationScript, /command === 'mark-published'[\s\S]*writePublishedResult/);
assert.match(publicationScript, /validatePublicationRequest\(next\)/);
assert.match(publicationScript, /fs\.writeFileSync\(temporaryPath/);
assert.match(publicationScript, /fs\.renameSync\(temporaryPath, targetPath\)/);
assert.match(workflow, /test "\$\(git rev-parse origin\/editorial\/tina\)" = "\$\{GITHUB_SHA\}"/);
assert.match(workflow, /git add -- src\/data\/editorial\/publication-request\.json/);
assert.doesNotMatch(workflow, /git add \.|git add -A|force|TINA_TOKEN|NETLIFY_AUTH_TOKEN/);
assert.doesNotMatch(packageJson, /supabase/i);

assert.doesNotMatch(workflow, /gh pr checks/);
assert.match(workflow, /test "\$quality_status" = "completed"/);
assert.match(workflow, /test "\$quality_conclusion" = "success"/);

assert.match(qualityWorkflow, /workflow_dispatch:/);
assert.match(qualityWorkflow, /test:netlify-ignore-build/);

assert.match(dashboard, /Guardar actualiza la vista previa/);
assert.match(dashboard, /Publicar cambios/);
assert.match(dashboard, /todos los cambios que revisaste/);
assert.match(dashboard, /publicationConfirmed/);
assert.match(dashboard, /NEXT_PUBLIC_EDITORIAL_PREVIEW_URL/);
assert.match(dashboard, /role="alert"/);
assert.match(dashboard, /aria-live="polite"/);
assert.match(dashboard, /window\.setInterval/);
assert.match(dashboard, /#\/screens\/panel_editorial/);
assert.match(dashboard, /close\?\.\(\)/);
assert.match(dashboard, /window\.location\.replace/);
assert.match(dashboard, /document\.visibilityState/);
assert.match(dashboard, /Información para pedir ayuda/);
assert.match(dashboard, /localReviewEnabled = process\.env\.TINA_PUBLIC_IS_LOCAL === 'true'/);
assert.match(dashboard, /Esta prueba no guarda, no publica ni llama servicios externos/);
assert.match(dashboard, /Herramientas de prueba local/);
assert.match(dashboard, /Cuando termine, el panel confirmará si esta versión ya está visible/);
assert.match(dashboard, /formatEditorialDateTime/);
assert.match(dashboard, /EDITORIAL_HISTORY_QUERY/);
assert.match(dashboard, /createEditorialPublicationHistoryView/);
assert.match(dashboard, /Ver movimientos recientes/);
assert.match(dashboard, /visibleHistoryView|visibleHistoryMovements/);
assert.match(dashboard, /setVisibleHistoryCount\(\(current\) => current \+ 5\)/);
assert.match(dashboard, /localHistoryScenarios/);
assert.match(dashboard, /Historial no disponible/);
assert.match(dashboard, /aria-labelledby="publication-history-title"/);
assert.doesNotMatch(dashboard, /Referencia: \{supportRequestId\}/);
assert.match(dashboard, /Forma de ver los contenidos/);
assert.match(dashboard, /<th scope="col">Estado<\/th>/);
assert.match(dashboard, /<th scope="col">Qué pasa<\/th>/);
assert.match(dashboard, /getEditorialDashboardDisplayState/);
assert.match(dashboard, /odontopau-editorial-content-view/);
assert.match(dashboard, /window\.localStorage\.getItem/);
assert.match(dashboard, /window\.localStorage\.setItem/);
assert.match(dashboard, /Contenidos por página/);
assert.match(dashboard, /odonto-dashboard-pagination-separator/);
assert.match(dashboard, /paginatedRows\.map/);
assert.match(dashboard, /aria-label="Desplazar la tabla hacia la izquierda"/);
assert.match(dashboard, /aria-label="Desplazar la tabla hacia la derecha"/);
assert.match(dashboard, /scrollBy\(\{ left: direction === 'left' \? -distance : distance, behavior: 'smooth' \}\)/);
assert.match(dashboard, /Tabla de contenidos\. Desplazá horizontalmente para ver todas las columnas\./);
assert.match(dashboard, /aria-label=\{`\$\{row\.actionLabel\}: \$\{row\.title\}`\}/);
assert.match(dashboard, /aria-label=\{`Ver vista previa de \$\{row\.title\}; se abre en otra pestaña`\}/);
assert.doesNotMatch(dashboard, /odonto-dashboard-table tbody[^\n]+display: block/);
assert.match(dashboard, /publicationInteractionEnabled = publicationEnabled && !localReviewEnabled/);

assert.match(netlifyConfig, /ignore = "node \.\/scripts\/netlify-ignore-build\.mjs"/);
assert.match(netlifyConfig, /for = "\/deployment\.json"/);
assert.match(packageJson, /write-deployment-marker\.mjs/);

console.log('--- Editorial publication workflow ---');
console.log('- Disparo cerrado, snapshot inmutable, PR protegido y staging sincronizado: presentes.');
console.log('- Sin force-push, staging amplio, secretos de Tina o credenciales de Netlify.');
console.log('- Tabla responsive con desplazamiento, controles laterales y navegación por teclado: presente.');
